# SPDX-FileCopyrightText: 2021 Andreas Härtel <http://andreashaertel.anno1982.de/>
# SPDX-License-Identifier: LGPL-3.0-or-later
# SPDX-PackageName: parameter_handler
# SPDX-PackageHomePage: https://github.com/andreashaertel/parameter_handler
################################################################################
#
# Makefile
# for the documentation of the C++ library parameter_handler
#
################################################################################

default: 
	@echo " Making the documentation using doxygen ... "; mkdir -p log; doxygen Doxyfile > log/make.log

clean: 
	@echo " Cleaning documentation ... "; rm -rf html; rm -rf latex; rm -rf log

